### ISSUE TITLE
Jump timing issue with couples/routine mode

### ISSUE THREAD

**Issue by ianklatzco** [stepmania/stepmania#1789]
I mentioned this in IRC, but wanted to post it somewhere publicly-indexed.

---

Context: We run a yearly couples tournament at [RIP](rip.ddrillini.club).
SM5 rates jumps differently from 3.95. Couples in 3.95 are actually a doubles chart.
The second player's notes are offset by a 1/192nd, and there's a negative warp/stop? value that moves them to the correct timing.

I believe SM5 made a change that breaks this: all jumps receive the same judgment. this breaks couples for our (tournament) use case, because two separate players get different timings.

(this may be for doubles only, i'm unsure about routine in SM5)
(some more info about the problem: https://twitter.com/pluto_chan/status/932608291011809280)

would anyone happen to know if routine mode that this issue?

from tertu in IRC:
```
in routine mode all notes are judged together
on the same row
it's more that's the way the people who implemented it believed it should be
```

---

Our current solution is to switch to 3.95 via a wireless button, which allows any DDRIllini members to use the couples game mode. It works for our purposes, but I'd love to get SM5 support.

(Maintaining a 3.95 setup is also nice for legacy mods content that hasn't been converted by @MrThatKid, yet. thank you for all your work!)

**Comment by shakesoda** [comment]
do both couples and routine modes have this problem? they're not the same thing - and this behavior is correct for routine.

**Comment by ianklatzco** [comment]
according to tertu, yes (see quoted block above)

**Comment by ianklatzco** [comment]
after some research:
* routine mode works by coloring rolls, and rows with rows on them, a different color. this appears to reflect how Only One Couples works.
* as tertu said, routine mode scores notes on the same beat as jumps (ie, the later player's timing is the total timing.
* neither lambda nor simply love expose routine mode charts in a player-accessible way
* the 192nd & stops thing appears to be a spooty-created hack to address the "jumps count as one judgment" timing issue. maybe it's like this for 3.95
   * the reason this doesn't cause visual stutters is that at reasonable high bpms (>80), they're sub-16ms (ie sub-frame).

for my purposes, i think i'll continue with the 192nd hack and-couples-are-doubles for RIP11.

todo/roadmap for 192nd hack:
* make a sm5.1 compatible noteskin for couples
* done?
* maybe fgchanges (for runaround prompts) need to be fixed.

todo/roadmap for proper fix (hard and i don't know how i'd do it):
* add to the SSC/SM spec for routine charts for a 2nd player
* have jumps judged based on that second player

**Comment by ianklatzco** [comment]
![image](https://user-images.githubusercontent.com/1487413/52593961-e43b7600-2e0f-11e9-97d9-d3292ce40a3c.png)

**Comment by ianklatzco** [comment]
Here's a script that converts SM5 routine to our 192nd hack: http://r21freak.com/SpootyBiscuit/Couples/Couple%20Conversion%20(py).rar

**Comment by dguzek** [comment]
Maybe helpful, here are my (old) notes on routine mode in SM5:

---

## SM5 Routine Mode as of Aug 27, 2014


0. On my ScreenSelectMusic, I made Routine charts accessible if Versus style
was selected on ScreenSelectStyle with AutoSetStyle set to true by hijacking
`StepsTypesToHide=CustomSetStyle()` and reloading metrics before ScreenSelectMusic. 

```lua
function CustomSetStyle()
	local StepsToHide = "dance-couple,dance-solo,dance-routine"
	
	if SL.Global.CurrentStyle == "None" then
		StepsToHide = ""
	elseif SL.Global.CurrentStyle == "Versus" or SL.Global.CurrentStyle == "Single" then
		StepsToHide = "dance-double,dance-couple,dance-solo"
	elseif SL.Global.CurrentStyle == "Double" then
		StepsToHide = "dance-single,dance-couple,dance-solo"
	end
	
	return StepsToHide
end
```


## ISSUES:

1.  Both players need to be joined, but all input goes to P1 (hardcoded? unsure.)
in gameplay, so P2 rapidly fails and earns no points.  This does not happen with AutoplayCPU.


2.  P1's gameplay modifiers are used; P2's are ignored.  Not necessarily a problem,
per se, but confusing initially.


3.  Noteskins are (more or less) forced by _fallback metrics:

RoutineNoteSkinP1=RoutineSkinP1()
RoutineNoteSkinP2=RoutineSkinP2()

Those functions are defined in 03 Gameplay.lua, and simply return strings 
dependent on game:

```lua
local RoutineSkins = {
	dance	= { P1 = "midi-routine-p1", P2 = "midi-routine-p2" },
	pump	= { P1 = "cmd-routine-p1", P2 = "cmd-routine-p2" },
	kb7		= { P1 = "default", P2 = "retrobar" },
	-------------------------------------------------------------
	default	= { P1 = "default", P2 = "default" }
}
```

Again, not a problem, per se, but worth... thinking about.


4. P1 must be the MasterPlayer via my #0 hack.  If P2 was the MasterPlayer,
Routine steps were not listed in the stock MusicWheel.


5. Arguably unrelated, but with my #0 hack, if P2 selected double style, the
music wheel displayed ONLY routine steps.  If P1 selected double style, double
steps were shown properly (and routine hidden, correctly) but that player was
forced to use P1's input.   Pressing P2's start could latejoin P2 which would
crash when any song was selected.


6. Since single steps and routine steps could coexist in my MusicWheel, I tried
entering PlayerOptions while P1 was on a routine steps and P2 on a single steps.
P2 was ignored; my ScreenPlayerOptions only listed the routine steps as selectable.
The inverse scenario held true; with P1 on a single steps and P2 on a routine,
ScreenPlayerOptions only listed the single steps as selectable.  This was actually
better than I'd anticipated (I was expecting a crash), but I'm noting it here.


7. _fallback's `IsRoutine()` method could stand to be improved for the sake of themers.
For example, it works properly ScreenGameplay (used it in my ScreenFilter code) but not
ScreenPlayerOptions (when you are currently already locked into playing a routine chart).

**Comment by ianklatzco** [comment]
I've tested. It looks like SM5 converts negative stops to warps (if you re-save the simfile in the editor, the SSC will have warps, tho the sm will still have negative stops). There is no difference in behavior between the two while playing.

It seems SM5 broke Spooty's hack to judge two players in couples differently.

I imagine I'll have to modify SM5 source to fix this problem.

**Comment by ianklatzco** [comment]
Possible locations:
* ScoreKeeper*.cpp
* TimingData.cpp
* ScreenGameplay.cpp

Pausing for now.

**Comment by ianklatzco** [comment]
I'm interested in discussing whether couples and routine should be separate.

Basically, there's two potential games here:
 * Versus doubles
 * Cooperative doubles

"Routine" is, I believe what it's named on the pump side of the house. "Couples" is what it's named on the ITG customs side of the house. I think it should be internally called couples, and exposed as such as well.

One idea: engine exposes both scores: versus and coop. Lua can choose which of these to display.

In any case, I think the routine/couples distinction should be removed. *very* few charts have been written for these modes, if any.

Here's where routine/couples are defined (GameManager.cpp): https://github.com/stepmania/stepmania/blob/27fdfb38718474253aeb33e9f9c7fd1a91ed823a/src/GameManager.cpp#L432

**Comment by ianklatzco** [comment]
I've modified Simply Love to expose routine on the `couples` branch of the [DDRIllini fork](https://github.com/ddrillini/Simply-Love-SM5/tree/couples).

There are a few engine bugs, as per Dan's notes.

I would recommend naming them Versus and Coop Couples. I suggest that the choice between the two be at this screen of Simply Love:

![image](https://user-images.githubusercontent.com/1487413/53285821-1fe91080-372b-11e9-905f-2dea2afaa118.png)

Handling high scores between the two different modes is a decision that needs to be made. If they're separate `Style`s, this is easy. Otherwise, I am less sure.

Personally, I don't really care about versus doubles, but I see why it's useful/interesting. I think there could be some very interesting charts, but I think they would not be terribly commonly used, because a skill comparison for doubles isn't really something people care about, and it's very hard to have fair charts (you'd need the same patterning twice, which doesn't really work musically in most cases). I don't see why you'd want a versus doubles mode to track separate scoring.

So, I think that the best option is to have one couples `Style` in the engine, and have the theme-side distinction between individual and collaborative scores. For my use case and modification to Simply Love, I will most likely print all three scores (coop and 2 indiv.).

I think I will:
* Rename routine style to couples.
* Scrap couples style.

@shakesoda, I am interested in your opinion on my conclusions here, and if you think they're the right way to proceed or not.

**Comment by ianklatzco** [comment]
Well, I:
* spent 3 hours spelunking through cpp source
* spent 3 hours spelunking through fallback and simply love lua

SL: given a chart w 32 notes, i'll have 32 misses on P1 if I don't do anything. P2 will have nothing (0 misses).

(Keep in mind stepmania will lie to you and only show you notes from P2 in the total note count on MusicSelect. Another bug, I guess.)

Fallback handles couples in a more reasonable way; namely, that all input is forced to P1. P2 still gets 32 misses (32), but P1 gets 32 inputs.

It seems that fallback has both ?players? actually enabled? And SL doesn't?

From diving through C++, I learned (again) that stepmania is terrible spaghetti.

**Comment by ianklatzco** [comment]
Okay, routine mode works in simply love.... if you go into the player modifiers menu.

SL must not be setting something it expects/needs; if you don't go into that menu.

**Comment by ianklatzco** [comment]
I had a theory that spootycouples might work if you go into the modifier menu.

They kind of do. Combo won't break, but some notes will fly past the receptors, even if you hit them with a timing window that wouldn't break combo.

This is probably due to negative stops being implemented differently than they are in 3.95.

It might be possible to look at the implementation, but I wouldn't really want to alter it for fear of breaking other mods charts. So, I probably just need to write a script to convert spootycouples to sm5couples, which should be doable because I already have a script to do the inverse.

**Comment by dguzek** [comment]
I had thought that spooty-style routine charts were written in SM5 to begin with and then converted to use negative stops [via a script](https://github.com/ddrillini/uiuc-wendy/tree/master/couples/convert-sm5routine-to-3.95double).

I guess I don't understand why they would need to be re-converted to their original format.  There is likely context I am missing.

**Comment by ianklatzco** [comment]
He's done it in one of two ways; either in SM5 and converted; or written in NotITG directly to the stops format (alan implemented it for him at some point within the past year or two).

I have a collection of his charts in spootycouples format; I'll need to convert them to sm5 couples to make them compatible with SM5.

**Comment by ianklatzco** [comment]
* if you don't go into modifiers; it loads two copies of the notes. you can view this by setting p1 and p2 to different speedmods.
* if you do go into modifiers, it only loads P1, which is decently playable.

So the question is, what is it that's set by going into the modifiers menu that makes only P1's arrows set up?

**Comment by ianklatzco** [comment]
have minimum viable: https://github.com/ianklatzco/stepmania/commit/fd89f8dcb7502e2c715d0238cbced1a243ae2123

**Comment by ianklatzco** [comment]
wrote a spec https://docs.google.com/document/d/1PHtRXs2SQDGEPJOZDl__Pxy0UAXcDorB1Qc8O17xAYE/edit

**Comment by dguzek** [comment]
Thank you for continuing to work on this.

**Comment by ianklatzco** [comment]
Description of the first major bug:

The input being fed to Stepmania is one press on the P2 left arrow at the time the note crosses the receptors.

Currently (5.1-new), in routine mode, notes on the same beat are treated the same as a jump in singles; if you try hitting only half of it, you miss it completely:

![bug-present](https://user-images.githubusercontent.com/1487413/61474726-d48c0480-a94e-11e9-91a4-6b1d54738a4e.gif)

![image](https://user-images.githubusercontent.com/1487413/61475099-b1158980-a94f-11e9-9e56-b19322244e5a.png)


By using an engine feature called `CountNotesSeparately`, I instead make it so that jump are judged individually in https://github.com/ianklatzco/stepmania/commit/fd89f8dcb7502e2c715d0238cbced1a243ae2123:

![bug-fixed](https://user-images.githubusercontent.com/1487413/61474772-f1283c80-a94e-11e9-8c9e-a61690e9716c.gif)
![image](https://user-images.githubusercontent.com/1487413/61475340-31d48580-a950-11e9-9938-b1f9dc4acc7b.png)

Amusingly, P1 and P2 *both* have misses registered in the Simply Love, but P1 has a fantastic in the arrow breakdown pane, despite still having 0% score:
![image](https://user-images.githubusercontent.com/1487413/61475393-4fa1ea80-a950-11e9-9024-6fcfed50d529.png)


This makes couples playable. However, scoring is still an outstanding issue. Players should either be scored as one, with one set of fantastics/excellent/etc shared, or scored separately, with a displayed cumulative score. A jump (two eg blue P1 arrows) should count as a single note to match singles behavior. By using `CountNotesSeparately`, 

 Here is a [gdoc spec](https://docs.google.com/document/d/1PHtRXs2SQDGEPJOZDl__Pxy0UAXcDorB1Qc8O17xAYE/edit) detailing the desire behavior.

**Comment by ianklatzco** [comment]
@geefr poked for a little bit, but his branch isn't currently in a compilable state: "Player::UpdateJudgedRows: Prevent players being judged for failing to hit other player's notes": https://github.com/geefr/stepmania/commit/c70296ea4247b2267ecb21a3d35a9f1828d7f136

**Comment by ianklatzco** [comment]
Looks like I’ll have to understand simfile loading from disk > how it’s stored in memory > how the game loads it per player > how the game tracks judgments.

I’ll have to pick between eg loading two instances of notes or just one, loading two instances of scorekeeper or just one, should we use two scorekeepernormals or one shared.

**Comment by ianklatzco** [comment]
how does bseparately work for judgment? i think you might still need to hit both parts of the jump to get a single judgment, but i’m not entirely sure because i was testing it on couples, which has broken judgments.

**Comment by ianklatzco** [comment]
found part of a manifestation of the options bug: 

* `Player`'s constructor has a `bVisibleParts` argument. 
* if you enter options menu, this is set to false. so, the second NoteField is still loaded; it's simply not drawn.

**Comment by ianklatzco** [comment]
Settling on the Simply Love bug that causes two sets of notes to be visible:

* If you just play (not entering the options menu) you load into ScreenGameplayNormal (visible in the F3 menu as `ScreenGameplay`).
* If you enter the options menu before playing, you load into ScreenGameplayShared. This is the one that only draws one set of arrows.

I am not super familiar with how Simply Love and the game engine interact w.r.t. screen transitions.

**Comment by ianklatzco** [comment]
Found a way to fix it!

https://github.com/ianklatzco/Simply-Love-SM5/commit/691e00ac86d0fe3c845305ae8476c05d00532f51

I'm not sure it's the cleanest (though it's only a few lines), but if someone of a better way then they'll probably comment when I submit for PR c:

**Comment by dguzek** [comment]
Thank you for continuing to work on this, still.

Thank you, especially, for documenting your findings as they occur in this thread.  This sort of weeks-long journey through unfamiliar source code is pretty typical, but documenting it like this, in a manner that exists outside your mind, seems to not be.  

The details within are immediately practical (some bits inevitably end up being false leads, but they can still help inform others who read and link to this public thread) and the larger story that emerges is both quieting and necessary.

**Comment by ianklatzco** [comment]
It looks like Simply Love reimplements judgments somehow, based on `Simply-Love-SM5/BGAnimations/ScreenGameplay\ overlay/PerColumnJudgmentTracking.lua` existing, though I haven't really read it in depth. Seems like it might cause issues for me.

**Comment by quietly-turning** [comment]
> It looks like Simply Love reimplements judgments somehow, , based on `Simply-Love-SM5/BGAnimations/ScreenGameplay overlay/PerColumnJudgmentTracking.lua` existing

That file just listens for judgment data broadcast from the engine via `JudgmentMessageCommand`, puts it into a table as it occurs, and then stores in the global SL table so that it persists between screens, allowing per-column judgment breakdowns to be shown later in ScreenEvaluation.

I'll add more comments to `./BGAnimations/ScreenGameplay overlay/PerColumnJudgmentTracking.lua` so that this is more clear to future spelunkers.

> Seems like it might cause issues for me.

Unlikely, but I guess it depends on what you're trying to do.

**Comment by quietly-turning** [comment]
> I'll add more comments to `./BGAnimations/ScreenGameplay overlay/PerColumnJudgmentTracking.lua` so that this is more clear to future spelunkers.

As promised: https://github.com/dguzek/Simply-Love-SM5/commit/557f51352924c3f07a5130c869e17f6f531fab6a

I'll make an effort to do the same with all files in `./BGAnimations/ScreenGameplay underlay/`, but I may not get to it this release cycle.

**Comment by aeubanks** [comment]
I took a look at routine mode.
The issue of all inputs being P1 is in `HandleInputEvents`
```
input.pn = INPUTMAPPER->ControllerToPlayerNumber( input.GameI.controller );
```
Apparently all input events must have a player associated with them, then that `Player` eventually handles the input event.
```
#0  Player::Step(int, int, RageTimer const&, bool, bool)
    (this=0x5555576ae6c0, col=3, row=-1, tm=..., bHeld=<optimized out>, bRelease=<optimized out>)
    at /stepmania/src/Player.cpp:1991
#1  0x00005555560fb9d0 in ScreenGameplay::Input(InputEventPlus const&) (this=0x555560743940, input=...)
    at /stepmania/src/ScreenGameplay.cpp:2600
#2  0x0000555555d0144f in ScreenManager::Input(InputEventPlus const&) (this=0x55555fd348d0, input=...)
    at /stepmania/src/ScreenManager.cpp:551
#3  0x0000555555c57cfb in HandleInputEvents(float) (fDeltaTime=<optimized out>)
    at /stepmania/src/StepMania.cpp:1614
#4  0x0000555555c4d5ef in GameLoop::UpdateAllButDraw(bool) (bRunningFromVBLANK=<optimized out>)
    at /stepmania/src/GameLoop.cpp:290
#5  0x0000555555c4e5f7 in GameLoop::RunGameLoop() () at /stepmania/src/GameLoop.cpp:320
#6  0x0000555555c55497 in sm_main(int, char**) (argc=<optimized out>, argv=<optimized out>)
```

The issue is we want to know the player before sending off the event. I tried some way of looking at the closest note and looking at its `PlayerNumber` but got annoyed with the codebase.


The issue with weird things happening with lifebars seems to be because of various calls to `LastTapNoteWithResult` not properly passing the `PlayerNumber` as the last parameter. Fixing those up seemed to help, but I ended up stuck at the bigger "all inputs are P1" issue. Maybe the other functions in `NoteDataWithScoring` also need to have their callers checked. And I'm not sure if `Player::GetClosestNoteDirectional` needs to filter out notes that belong to another player. Probably...
This might solve the jump issue thing since each `Player` would ideally only be able to see and judge its own notes.

A little off topic, but apparently there's a shared lifebar mechanic that might be good for routine if it were hooked up?

**Comment by ianklatzco** [comment]
thanks for the work! excited to see other people interested in this issue.

**Comment by ianklatzco** [comment]
i too got fatigued with the codebase, haha. seems like it'd be quite the mapping effort to untangle it.

**Comment by ianklatzco** [comment]
@CrashCringle12 reports that he has exciting news about couples sometime soon :^)
