### ISSUE TITLE
Fatal I/O error communicating with X server. - Multiples times

### ISSUE THREAD

**Issue by latot** [stepmania/stepmania#913]
Hi, here is this https://github.com/stepmania/stepmania/issues/906 but with more info and complete, well, this happend when i close sm with the "X" of the topbar, and i have some logs with differents conditions, and only with one condition sm generate the crashinfo file.

First: Starting the system, open Sm and the close it in the first screen
Bug: Segmentation fault - address not mapped at 0x00007ffd8a769fa8
crashinfo: https://gist.github.com/latot/6cb5972d484e3d6bf4ed
note 1: i can't get the bt of this.
note 2: if you run ldconfig before sm, you can skip this and will show one of the nexts errors.

Second: Close Sm before the first screen (in the firsts 0-1.5 seconds of blackscreen)
bug: Fatal I/O error communicating with X server.
bt:
```
Breakpoint 1, FatalCallback (d=0x3974d20) at /home/pipe/Documentos/git/stepmania/src/archutils/Unix/X11Helper.cpp:107
107		RageException::Throw( "Fatal I/O error communicating with X server." );
(gdb) bt
#0  FatalCallback (d=0x3974d20) at /home/pipe/Documentos/git/stepmania/src/archutils/Unix/X11Helper.cpp:107
#1  0x00007ffff145eaaf in _XIOError (dpy=0x3974d20) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/XlibInt.c:1498
#2  0x00007ffff145a900 in _XEventsQueued (dpy=0x3974d20, mode=1) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/xcb_io.c:366
#3  0x00007ffff142c228 in XCheckWindowEvent (dpy=0x3974d20, w=29360130, mask=2097231, event=0x7fffffffcfb0)
    at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/ChkWinEv.c:79
#4  0x0000000000cdc400 in InputHandler_X11::Update (this=0x3b4be60) at /home/pipe/Documentos/git/stepmania/src/arch/InputHandler/InputHandler_X11.cpp:187
#5  0x0000000000f18cde in RageInput::Update (this=0x3b439b0) at /home/pipe/Documentos/git/stepmania/src/RageInput.cpp:76
#6  0x0000000000a64286 in InputFilter::Update (this=0x1e2f300, fDeltaTime=19.5795631) at /home/pipe/Documentos/git/stepmania/src/InputFilter.cpp:317
#7  0x0000000000a0b427 in HandleInputEvents (fDeltaTime=19.5795631) at /home/pipe/Documentos/git/stepmania/src/StepMania.cpp:1498
#8  0x0000000000a03476 in GameLoop::RunGameLoop () at /home/pipe/Documentos/git/stepmania/src/GameLoop.cpp:294
#9  0x0000000000a09a98 in sm_main (argc=1, argv=0x7fffffffd6f8) at /home/pipe/Documentos/git/stepmania/src/StepMania.cpp:1214
#10 0x00000000010e8e50 in main (argc=1, argv=0x7fffffffd6f8) at /home/pipe/Documentos/git/stepmania/src/Main.cpp:5
```
Third: Close sm in the first screen
Bug: Fatal I/O error communicating with X server
bt:
```
Breakpoint 1, FatalCallback (d=0x3993e10) at /home/pipe/Documentos/git/stepmania/src/archutils/Unix/X11Helper.cpp:107
107		RageException::Throw( "Fatal I/O error communicating with X server." );
(gdb) bt
#0  FatalCallback (d=0x3993e10) at /home/pipe/Documentos/git/stepmania/src/archutils/Unix/X11Helper.cpp:107
#1  0x00007ffff145eaaf in _XIOError (dpy=0x3993e10) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/XlibInt.c:1498
#2  0x00007ffff145b75c in _XReply (dpy=0x3993e10, rep=0x7fffffffd070, extra=0, discard=0) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/xcb_io.c:708
#3  0x00007ffff4f7984b in DRI2GetBuffersWithFormat (dpy=0x3993e10, drawable=29360130, width=0x222a328, height=0x222a32c, attachments=0x7fffffffd170, count=1, 
    outCount=0x7fffffffd1d0) at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/glx/dri2.c:490
#4  0x00007ffff4f7b745 in dri2GetBuffersWithFormat (driDrawable=0x222a300, width=0x222a328, height=0x222a32c, attachments=0x7fffffffd170, count=1, 
    out_count=0x7fffffffd1d0, loaderPrivate=0x49af590) at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/glx/dri2_glx.c:900
#5  0x00007fffd1b9688c in intel_query_dri2_buffers (brw=0x4e14268, drawable=0x222a300, buffers=0x7fffffffd1d8, buffer_count=0x7fffffffd1d0)
    at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/mesa/drivers/dri/i965/brw_context.c:1307
#6  0x00007fffd1b9631a in intel_update_dri2_buffers (brw=0x4e14268, drawable=0x222a300)
    at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/mesa/drivers/dri/i965/brw_context.c:1123
#7  0x00007fffd1b96525 in intel_update_renderbuffers (context=0x3e70230, drawable=0x222a300)
    at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/mesa/drivers/dri/i965/brw_context.c:1179
#8  0x00007fffd1b965a7 in intel_prepare_render (brw=0x4e14268) at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/mesa/drivers/dri/i965/brw_context.c:1198
#9  0x00007fffd1b88e8a in brw_clear (ctx=0x4e14268, mask=18) at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/mesa/drivers/dri/i965/brw_clear.c:234
#10 0x00007fffd17d16b6 in _mesa_Clear (mask=16640) at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/mesa/main/clear.c:222
#11 0x0000000000ee66dc in RageDisplay_Legacy::BeginFrame (this=0x3784860) at /home/pipe/Documentos/git/stepmania/src/RageDisplay_OGL.cpp:794
#12 0x0000000000ae46d7 in ScreenManager::Draw (this=0x3ba8370) at /home/pipe/Documentos/git/stepmania/src/ScreenManager.cpp:485
#13 0x0000000000a03518 in GameLoop::RunGameLoop () at /home/pipe/Documentos/git/stepmania/src/GameLoop.cpp:308
#14 0x0000000000a09a98 in sm_main (argc=1, argv=0x7fffffffd6f8) at /home/pipe/Documentos/git/stepmania/src/StepMania.cpp:1214
#15 0x00000000010e8e50 in main (argc=1, argv=0x7fffffffd6f8) at /home/pipe/Documentos/git/stepmania/src/Main.cpp:5
```
Fourth: Close Sm from other screen
Bug: Fatal I/O error communicating with X server
bt:
```
Breakpoint 1, FatalCallback (d=0x3975250) at /home/pipe/Documentos/git/stepmania/src/archutils/Unix/X11Helper.cpp:107
107		RageException::Throw( "Fatal I/O error communicating with X server." );
(gdb) bt
#0  FatalCallback (d=0x3975250) at /home/pipe/Documentos/git/stepmania/src/archutils/Unix/X11Helper.cpp:107
#1  0x00007ffff145eaaf in _XIOError (dpy=0x3975250) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/XlibInt.c:1498
#2  0x00007ffff1459997 in require_socket (dpy=0x3975250) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/xcb_io.c:70
#3  0x00007ffff145aec6 in _XFlush (dpy=0x3975250) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/xcb_io.c:511
#4  0x00007ffff145ef60 in _XGetRequest (dpy=0x3975250, type=43 '+', len=4) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/XlibInt.c:1735
#5  0x00007ffff14550e0 in XSync (dpy=0x3975250, discard=0) at /var/tmp/portage/x11-libs/libX11-1.6.2/work/libX11-1.6.2/src/Sync.c:43
#6  0x00007ffff4f7b44c in dri2XcbSwapBuffers (dpy=0x3975250, pdraw=0x4270b30, target_msc=0, divisor=0, remainder=0)
    at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/glx/dri2_glx.c:815
#7  0x00007ffff4f7b5d2 in dri2SwapBuffers (pdraw=0x4270b30, target_msc=0, divisor=0, remainder=0, flush=1)
    at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/glx/dri2_glx.c:853
#8  0x00007ffff4f38d4f in glXSwapBuffers (dpy=0x3975250, drawable=29360130) at /var/tmp/portage/media-libs/mesa-10.5.8/work/mesa-10.5.8/src/glx/glxcmds.c:842
#9  0x0000000000ce2997 in LowLevelWindow_X11::SwapBuffers (this=0x1a3f9b0) at /home/pipe/Documentos/git/stepmania/src/arch/LowLevelWindow/LowLevelWindow_X11.cpp:300
#10 0x0000000000ee6741 in RageDisplay_Legacy::EndFrame (this=0x373d780) at /home/pipe/Documentos/git/stepmania/src/RageDisplay_OGL.cpp:802
#11 0x0000000000ae482a in ScreenManager::Draw (this=0x3a66ea0) at /home/pipe/Documentos/git/stepmania/src/ScreenManager.cpp:500
#12 0x0000000000a03518 in GameLoop::RunGameLoop () at /home/pipe/Documentos/git/stepmania/src/GameLoop.cpp:308
#13 0x0000000000a09a98 in sm_main (argc=1, argv=0x7fffffffd6f8) at /home/pipe/Documentos/git/stepmania/src/StepMania.cpp:1214
#14 0x00000000010e8e50 in main (argc=1, argv=0x7fffffffd6f8) at /home/pipe/Documentos/git/stepmania/src/Main.cpp:5
```

I can confirm this on gentoo 64 and ubuntu wily x64
Thx all.

**Comment by kyzentun** [comment]
So, when you forcibly close stepmania's window, it throws an exception and exits.  Why is that a problem?

**Comment by latot** [comment]
mm, closing the close button of the windows its a force close?
well i was searching other thing, a mysterious ptrace error some times happend with a crash, so it can be related or not with other issues i really don't know, actually don't is a problem but i want post it to have a record of it.
