### ISSUE TITLE
Crash on start when running under Wayland

### ISSUE THREAD

**Issue by Wallacoloo** [stepmania/stepmania#960]
I am running a Gnome 3.18 Wayland session on 64-bit Arch Linux. Upon starting stepmania (latest git version as of today), I see the song-scanning splash screen, but then stepmania crashes when it tries to launch the full gui.

[Here's](https://gist.githubusercontent.com/Wallacoloo/577be31867e8b0885015/raw/4215b32d7d260358e1a96bac71c3e941949773ab/stdout.txt) a log of all the console output (note: it's *very* long). The GdkPixbuf messages have occurred ever since I started using using Stepmania on Gnome about 3 months ago. They don't occur on my Ubuntu system that's running XFCE, but I think they *may* be safe to ignore. The message that sticks out to me is:
```
/////////////////////////////////////////
WARNING: X11 Protocol error BadValue (integer parameter out of range for operation) (2) has occurred, caused by request 140,2, resource ID 65535
/////////////////////////////////////////
```

Note `resource ID = 65535`; `-1` if a 16 bit value.

This message is generated in the ErrorCallback function of[X11Helper.cpp:99](https://github.com/stepmania/stepmania/blob/536be1f64c215cdf53eadbf29926a2c5d82a4518/src/archutils/Unix/X11Helper.cpp#L99). If I set a breakpoint there, I get the following stack trace with gdb:

```
(gdb) bt
#0  ErrorCallback (d=0x6178310, err=0x7fffffffd450) at /home/colin/src/stepmania/src/archutils/Unix/X11Helper.cpp:98
#1  0x00007ffff2f4087d in _XError () from /usr/lib/libX11.so.6
#2  0x00007ffff2f3d7c7 in ?? () from /usr/lib/libX11.so.6
#3  0x00007ffff2f3e935 in _XReply () from /usr/lib/libX11.so.6
#4  0x00007ffff2872373 in XRRSetScreenConfigAndRate () from /usr/lib/libXrandr.so.2
#5  0x00007ffff2872492 in XRRSetScreenConfig () from /usr/lib/libXrandr.so.2
#6  0x0000000000d7631b in LowLevelWindow_X11::TryVideoMode (this=0x45f6e70, p=..., bNewDeviceOut=@0x7fffffffdccf: true)
    at /home/colin/src/stepmania/src/arch/LowLevelWindow/LowLevelWindow_X11.cpp:209
#7  0x0000000000f6d550 in RageDisplay_Legacy::TryVideoMode (this=0x2884e60, p=..., bNewDeviceOut=@0x7fffffffdccf: true)
    at /home/colin/src/stepmania/src/RageDisplay_OGL.cpp:734
#8  0x0000000000f606a7 in RageDisplay::SetVideoMode (this=0x2884e60, p=..., bNeedReloadTextures=@0x7fffffffdccf: true)
    at /home/colin/src/stepmania/src/RageDisplay.cpp:74
#9  0x0000000000f6be27 in RageDisplay_Legacy::Init (this=0x2884e60, p=..., bAllowUnacceleratedRenderer=false) at /home/colin/src/stepmania/src/RageDisplay_OGL.cpp:471
#10 0x0000000000aabbd5 in CreateDisplay () at /home/colin/src/stepmania/src/StepMania.cpp:786
#11 0x0000000000aaa408 in StartDisplay () at /home/colin/src/stepmania/src/StepMania.cpp:197
#12 0x0000000000aadad6 in sm_main (argc=1, argv=0x7fffffffe798) at /home/colin/src/stepmania/src/StepMania.cpp:1181
#13 0x0000000001169d69 in main (argc=1, argv=0x7fffffffe798) at /home/colin/src/stepmania/src/Main.cpp:5
```

[Here's](https://gist.githubusercontent.com/Wallacoloo/577be31867e8b0885015/raw/4215b32d7d260358e1a96bac71c3e941949773ab/crashinfo.txt) the /tmp/crashinfo.txt file which Stepmania created.

**Comment by shakesoda** [comment]
StepMania's windowing code is all really, really old and tied to X11. Try #716, if that doesn't work then this is unlikely to be fixed on our end until SM6.

**Comment by latot** [comment]
sadly seems 716 is not compatible with the master branch D:

log:
https://gist.github.com/latot/0cca6629d0bfb4c77bb6
